package com.kutaybezci.monsterFight.gui;

import com.kutaybezci.monsterFight.FightingThread;
import com.kutaybezci.monsterFight.Monster;
import com.kutaybezci.monsterFight.Question;
import com.kutaybezci.monsterFight.Session;
import com.kutaybezci.monsterFight.Translate;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author kutay.bezci
 */
public class FrmFight extends javax.swing.JFrame {
    private final Monster monster;

    public Monster getMonster() {
        return monster;
    }

    /**
     * Creates new form FrmFight
     * @param monster
     */
    public FrmFight(Monster monster) {
        initComponents();
        this.monster=monster;
        this.lblMonsterName.setText(monster.getName());
        this.lblPlayerName.setText(Session.getInstance().getPlayerName());
        this.barPlayerHealth.setMinimum(0);
        this.barPlayerHealth.setMaximum(this.monster.getPlayerHealth());
        this.barMonsterHealth.setMinimum(0);
        this.barMonsterHealth.setMaximum(this.monster.getHealth());
        this.txtDescription.setText(monster.getDescription());
        Translate.getInstance().translate(this.btnFight);
    }

    public void paintHealth(int monsterHealth, int playerHealth, int activeQuestion){
        this.barMonsterHealth.setValue(monsterHealth);
        this.barPlayerHealth.setValue(playerHealth);
        this.lblActive.setText(String.valueOf(activeQuestion));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMonsterName = new javax.swing.JLabel();
        barMonsterHealth = new javax.swing.JProgressBar();
        lblPlayerName = new javax.swing.JLabel();
        barPlayerHealth = new javax.swing.JProgressBar();
        lblFightIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnFight = new javax.swing.JButton();
        lblActive = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblMonsterName.setText("lblMonsterName");

        lblPlayerName.setText("lblPlayerName");

        lblFightIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swords.png"))); // NOI18N

        txtDescription.setEditable(false);
        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        btnFight.setText("btnFight");
        btnFight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFightIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMonsterName)
                            .addComponent(barMonsterHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlayerName)
                            .addComponent(barPlayerHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFightIcon)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMonsterName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barMonsterHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlayerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barPlayerHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblActive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFight)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFightActionPerformed
        this.btnFight.setEnabled(false);
        new FightingThread(this).start();
    }//GEN-LAST:event_btnFightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Monster monster=new Monster();
        monster.setName("Canavar");
        monster.setSecretMessage("Öldüm!");
        monster.setHealth(100);
        monster.setDescription("Kötü canavar");
        monster.setQuestions(new ArrayList<>());
        monster.setPlayerHealth(100);
        monster.setMaxActiveQuestion(3);
        Random random=new Random(System.currentTimeMillis());
        for(int i=0; i<10; i++){
            Question question=new Question();
            question.setScreenSeconds(20);
            question.setBonus(10);
            question.setPenalty(10);
            question.setBleed(1);
            int x=random.nextInt(10);
            int y=random.nextInt(10);
            question.setQuestion(String.format("%dX%d=?", x,y));
            question.setAnswer(String.valueOf(x*y));
            monster.getQuestions().add(question);
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFight(monster).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barMonsterHealth;
    private javax.swing.JProgressBar barPlayerHealth;
    private javax.swing.JButton btnFight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActive;
    private javax.swing.JLabel lblFightIcon;
    private javax.swing.JLabel lblMonsterName;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
