package com.kutaybezci.monsterFight.gui;

import com.kutaybezci.monsterFight.Question;
import com.kutaybezci.monsterFight.Translate;
import com.kutaybezci.monsterFight.Utils;
import java.util.function.BiConsumer;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author kutay.bezci
 */
public class FrmQuestionDisplay extends javax.swing.JFrame {

    private final FrmMonsterEditor examEditorFrm;
    private int index;

    /**
     * Creates new form QuestionDisplayFrm
     *
     * @param examEditorFrm
     * @param index
     */
    public FrmQuestionDisplay(FrmMonsterEditor examEditorFrm, int index) {
        initComponents();
        Translate.getInstance().translate(this);
        this.examEditorFrm = examEditorFrm;
        this.index = index;
        if (this.index > -1) {
            Question question = this.examEditorFrm.getQuestions().get(index);
            this.txtAnswer.setText(String.valueOf(question.getAnswer()));
            this.txtTime.setText(String.valueOf(question.getScreenSeconds()));
            this.txtBonus.setText(String.valueOf(question.getBonus()));
            this.txtQuestion.setText(String.valueOf(question.getQuestion()));
            this.txtPenalty.setText(String.valueOf(question.getPenalty()));
            this.txtBleed.setText(String.valueOf(question.getBleed()));
        } else {
            this.btnDelete.setVisible(false);
        }
    }

    public void translate() {
        Translate translate = Translate.getInstance();
        translate.translate(this.btnDelete);
        translate.translate(this.btnSave);
        translate.translate(this.lblAnswer);
        translate.translate(this.lblBleed);
        translate.translate(this.lblBonus);
        translate.translate(this.lblPenalty);
        translate.translate(this.lblQuestion);
        translate.translate(this.lblTime);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPenalty = new javax.swing.JLabel();
        txtPenalty = new javax.swing.JTextField();
        lblQuestion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        lblAnswer = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        lblBleed = new javax.swing.JLabel();
        txtBleed = new javax.swing.JTextField();
        lblBonus = new javax.swing.JLabel();
        txtBonus = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblPenalty.setText("lblPenalty");

        txtPenalty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenaltyActionPerformed(evt);
            }
        });

        lblQuestion.setText("lblQuestion");

        txtQuestion.setColumns(20);
        txtQuestion.setRows(5);
        jScrollPane1.setViewportView(txtQuestion);

        lblAnswer.setText("lblAnswer");

        lblTime.setText("lblTime");

        lblBleed.setText("lblBleed");

        lblBonus.setText("lblBonus");

        btnSave.setText("btnSave");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("btnDelete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnswer)
                    .addComponent(lblQuestion)
                    .addComponent(lblTime)
                    .addComponent(lblBonus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTime)
                                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBleed)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPenalty)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBleed)
                            .addComponent(txtPenalty))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnswer)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPenalty)
                    .addComponent(txtPenalty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(lblBleed)
                    .addComponent(txtBleed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBonus)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPenaltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenaltyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenaltyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (this.index > -1) {
            this.examEditorFrm.getQuestions().remove(this.index);
        }
        this.examEditorFrm.refreshTable();
        this.dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void setField(JTextComponent textField, String name, Question question, BiConsumer<Question, String> setter) {
        textField.requestFocus();
        if (Utils.isBlank(textField.getText())) {
            throw new RuntimeException(String.format("%s boş!", name));
        }
        setter.accept(question, textField.getText());

    }

    public void setIntegerField(JTextField textField, String name, Question question, BiConsumer<Question, Integer> setter) {
        textField.requestFocus();
        if (Utils.isBlank(textField.getText())) {
            throw new RuntimeException(String.format("%s boş!", name));
        }
        try {
            Integer intText = Integer.valueOf(textField.getText());
            setter.accept(question, intText);
        } catch (NumberFormatException ex) {
            throw new RuntimeException(String.format("%s sayısal değil", name));
        }
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Question question = new Question();
        try {
            Utils.setField(this.txtQuestion, this.lblQuestion.getText(), question, Question::setQuestion);
            Utils.setField(this.txtAnswer, this.lblAnswer.getText(), question, Question::setAnswer);
            Utils.setIntegerField(this.txtBleed, this.lblBleed.getText(), question, Question::setBleed);
            Utils.setIntegerField(this.txtTime, this.lblTime.getText(), question, Question::setScreenSeconds);
            Utils.setIntegerField(this.txtPenalty, this.lblPenalty.getText(), question, Question::setPenalty);
            Utils.setIntegerField(this.txtBonus, this.lblBonus.getText(), question, Question::setBonus);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
        if (this.index == -1) {
            this.examEditorFrm.getQuestions().add(question);
        } else {
            this.examEditorFrm.getQuestions().set(this.index, question);
        }
        this.examEditorFrm.refreshTable();
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmQuestionDisplay(null, -1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblBleed;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblPenalty;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtBleed;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtPenalty;
    private javax.swing.JTextArea txtQuestion;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
